<!DOCTYPE html>
<html lang="hr">

	<head>
		<title>Adria Gastro - admin panel</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilAdmin.css" />
		<link rel="stylesheet" type="text/css" href="./css/jquery-ui-1.11.4.min.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
		<script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
		<script src="./script/scriptAdmin.js" type="text/javascript"></script>
		<script src="./script/Chart.bundle-2.2.1.min.js" type="text/javascript"></script>
		<script src="./script/moment.min-2.14.1.js" type="text/javascript"></script>
	</head>

	<body>
		<button class="show_settings" type="submit">Sakrij postavke</button>
		<div id="admin_functions">
			<!-- MT to show graph -->
			<fieldset id="mt-choice-box-admin">
				<h3>Odaberite MT za prikaz glasova:</h3>
				<select id="mt_list" name="mt" class="mt_list_admin">
					<!-- Content generated by call -->
				</select>
				<div id="date_and_submit">
					<h3>Datum za prikaz: <input type="text" id="datepicker" value=""></h3>
					<h3>Korak u minutama: <input type="number" id="step_min" value="25"></h3>
					<button class="submit_button_graph" type="submit">Potvrdi odabir</button>
				</div>
			</fieldset>

			<!-- Add new MT -->
			<fieldset id="mt-add-box-admin">
				<h3>Dodavanje novog MT-a:</h2>
				<h3>Broj MT-a:</br><input type="number" id="new_mt_id" placeholder="npr.: 2540"></h3>
				<h3>Ime MT-a:</br><input type="text" id="new_mt_name" placeholder="npr.: Restoran Heinzelova"></h3>
				<button class="submit_button_add_mt" type="submit">Dodaj MT</button>
			</fieldset>

			<!-- Question -->
			<div id="question-box-admin">
				<!-- globally add new question -->
				<fieldset class="question-add-box-admin">
					<h3>Dodavanje pitanja:</h2>
					<input type="text" id="new_question_text">
					<button class="submit_button_add_question" type="submit">Dodaj Pitanje</button>
				</fieldset>

				<hr />

				<!-- set a specific question for a MT -->
				<fieldset class="question-set-box-admin">
					<h3>Odabir pitanja:</h3>
					<select id="q_list" name="customQuestionlist" class="q_list_admin">
						<!-- Content generated by call -->
					</select>
					
					<h3>Postavi odabrano pitanje na MT:</h3>
					<select id="mt_list_q" name="mt" class="mt_list_q_admin">
						<!-- Content generated by call -->
					</select>
					</br>
					<button class="submit_button_set_question" type="submit">Postavi pitanje</button>
				</fieldset>
			</div>
			
			<!-- Thanks text -->
			<div id="thanks-box-admin">
				<!-- globally add new thanks text -->
				<fieldset class="thanks-add-box-admin">
					<h3>Dodavanje teksta kod zahvale:</h2>
					<input type="text" id="new_thanks_text">
					</br>
					<button class="submit_button_thanks_message" type="submit">Dodaj Tekst</button>
				</fieldset>
				
				<hr />

				<!-- set a specific thanks for a MT -->
				<fieldset class="thanks-set-box-admin">
					<h3>Odabir teksta zahvale:</h3>
					<select id="thanks_list" name="customThankslist" class="thanks_list_admin">
						<!-- Content generated by call -->
					</select>
					
					<h3>Postavi tekst na sljedeće MT:</h3>
					<select id="mt_list_thanks" name="mt" class="mt_list_thanks_admin">
						<!-- Content generated by call -->
					</select>

					<button class="submit_button_set_thanks" type="submit">Postavi tekst</button>
				</fieldset>
			</div>

			<!-- Additional stuff -->
			<fieldset id="extern-functions-box-admin">
				<div id="ad-upload-content">
					<h3><a target="_blank" href="./ads/ad_pic.php">Postavke za Reklame</a></h3>
					<a target="_blank" href="./ads/ad_pic.php">
						<img src="./images/ad_icon.png" width="100" height="100" border="0" alt="Postavke za Reklame">
					</a>
				</div>
				<hr />
				<h3><a id="setTargetLink" target="_blank" href="./targets.php">Postavljanje targeta</a></h3>
			</fieldset>

		</div>
		<div hidden id="vote_charts">
			<div id="infoRight">
				<canvas id="votesRadarChart" height="333px"></canvas>
				<div id="targetTxt">Targeti:
					<div id="targets"></div>
				</div>
			</div>
			<canvas id="votesChartFirstQ" height="250px" width="1100px"></canvas>
			<canvas id="votesChartSecondQ" height="250px" width="1100px"></canvas>
			<canvas id="votesChartThirdQ" height="250px" width="1100px"></canvas>
			<canvas id="votesChartFourthQ" height="250px" width="1100px"></canvas>
			
		</div>

		<div id="footer"><hr />&copy; Antonio Prcela. All rights reserved.</div>
	</body>
</html>
