<!DOCTYPE html>
<html lang="hr">

	<head>
		<title>Admin panel</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilAdmin.css" />
		<link rel="stylesheet" type="text/css" href="./css/jquery-ui-1.11.4.min.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
		<script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
		<script src="./script/scriptAdmin.js" type="text/javascript"></script>
		<script src="./script/Chart.bundle-2.2.1.min.js" type="text/javascript"></script>
		<script src="./script/moment.min-2.14.1.js" type="text/javascript"></script>
	</head>

	<body>
		<button class="show_settings" type="submit">Hide settings</button>
		<div id="admin_functions">
			<!-- MT to show graph -->
			<fieldset id="mt-choice-box-admin">
				<h3>Choose place to show votes for:</h3>
				<select id="mt_list" name="mt" class="mt_list_admin">
					<!-- Content generated by call -->
				</select>
				<div id="date_and_submit">
					<h3>Date to show: <input type="text" id="datepicker" value=""></h3>
					<h3>Step (in minutes): <input type="number" id="step_min" value="25"></h3>
					<button class="submit_button_graph" type="submit">Submit choice</button>
				</div>
			</fieldset>

			<!-- Add new MT -->
			<fieldset id="mt-add-box-admin">
				<h3>Add new place:</h2>
				<h3>Place ID:</br><input type="number" id="new_mt_id" placeholder="npr.: 2540"></h3>
				<h3>Place name:</br><input type="text" id="new_mt_name" placeholder="npr.: Restoran Heinzelova"></h3>
				<button class="submit_button_add_mt" type="submit">Add place</button>
			</fieldset>

			<!-- Question -->
			<div id="question-box-admin">
				<!-- globally add new question -->
				<fieldset class="question-add-box-admin">
					<h3>Question adding:</h2>
					<input type="text" id="new_question_text">
					<button class="submit_button_add_question" type="submit">Add question</button>
				</fieldset>

				<hr />

				<!-- set a specific question for a MT -->
				<fieldset class="question-set-box-admin">
					<h3>Choose question:</h3>
					<select id="q_list" name="customQuestionlist" class="q_list_admin">
						<!-- Content generated by call -->
					</select>
					
					<h3>Set chosen question for this place:</h3>
					<select id="mt_list_q" name="mt" class="mt_list_q_admin">
						<!-- Content generated by call -->
					</select>
					</br>
					<button class="submit_button_set_question" type="submit">Set question</button>
				</fieldset>
			</div>
			
			<!-- Thanks text -->
			<div id="thanks-box-admin">
				<!-- globally add new thanks text -->
				<fieldset class="thanks-add-box-admin">
					<h3>Add info text (after vote submit):</h2>
					<input type="text" id="new_thanks_text">
					</br>
					<button class="submit_button_thanks_message" type="submit">Add text</button>
				</fieldset>
				
				<hr />

				<!-- set a specific thanks for a MT -->
				<fieldset class="thanks-set-box-admin">
					<h3>Choose info text:</h3>
					<select id="thanks_list" name="customThankslist" class="thanks_list_admin">
						<!-- Content generated by call -->
					</select>
					
					<h3>Set chosen question for following place:</h3>
					<select id="mt_list_thanks" name="mt" class="mt_list_thanks_admin">
						<!-- Content generated by call -->
					</select>

					<button class="submit_button_set_thanks" type="submit">Set text</button>
				</fieldset>
			</div>

			<!-- Additional stuff -->
			<fieldset id="extern-functions-box-admin">
				<div id="ad-upload-content">
					<h3><a target="_blank" href="./ads/ad_pic.php">Settings for ads</a></h3>
					<a target="_blank" href="./ads/ad_pic.php">
						<img src="./images/ad_icon.png" width="100" height="100" border="0" alt="Postavke za Reklame">
					</a>
				</div>
				<hr />
				<h3><a id="getXmlLink" target="_blank" href="./xls.php">Request data as XML</a></h3>
				<hr />
				<h3><a id="setTargetLink" target="_blank" href="./targets.php">Set Target values</a></h3>
			</fieldset>
		</div>

		<div hidden id="infoTarget">
			<canvas id="votesRadarChart" height="500px"></canvas>
			<div id="targetTxt"><h3>Targets:</h3></div>
			<div class="targetTxt_border"><h3>Week</h3><fieldset id="targets_w"></fieldset></div>
			<div class="targetTxt_border"><h3>Month</h3><fieldset id="targets_m"></fieldset></div>
			<div class="targetTxt_border"><h3>Quarter</h3><fieldset id="targets_q"></fieldset></div>
			<div class="targetTxt_border"><h3>Year</h3><fieldset id="targets_y"></fieldset></div>
		</div>

		<div hidden id="vote_charts">
			<canvas id="votesChartFirstQ" height="280px" width="1400px"></canvas>
			<canvas id="votesChartSecondQ" height="280px" width="1400px"></canvas>
			<canvas id="votesChartThirdQ" height="280px" width="1400px"></canvas>
			<canvas id="votesChartFourthQ" height="280px" width="1400px"></canvas>
		</div>

		<div id="footer"><hr />&copy; Antonio Prcela. All rights reserved.</div>
	</body>
</html>
