<!DOCTYPE html>
<html lang="hr">

	<head>
		<title>Adria Gastro - admin panel</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilAdmin.css" />
		<link rel="stylesheet" type="text/css" href="./css/jquery-ui-1.11.4.min.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
		<script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
		<script src="./script/scriptAdmin.js" type="text/javascript"></script>
		<script src="./script/Chart.bundle-2.2.1.min.js" type="text/javascript"></script>
		<script src="./script/moment.min-2.14.1.js" type="text/javascript"></script>
	</head>

	<body>

		<div id="admin_functions">
			<!-- MT to show graph -->
			<fieldset class="mt-choice-box-admin">
				<h3>Odaberite MT za prikaz glasova:</h3>
				<select id="mt_list" name="mt" class="mt_list_admin">
					<!-- Content generated by call -->
				</select>
				<div id="date_and_submit">
					<h3>Datum za prikaz: <input type="text" id="datepicker" value=""></h3>
					<button class="submit_button_graph" type="submit">Potvrdi odabir</button>
				</div>
			</fieldset>

			<!-- Add new MT -->
			<fieldset class="mt-add-box-admin">
				<h3>Dodavanje novog MT-a:</h2>
				<h3>Broj MT-a: <input type="text" id="new_mt_id"></h3>
				<h3>Ime MT-a: <input type="text" id="new_mt_name"></h3>
				<button class="submit_button_add_mt" type="submit">Dodaj MT</button>
			</fieldset>

			<!-- globally add new question -->
			<fieldset class="question-add-box-admin">
				<h3>Dodavanje pitanja:</h2>
				<input type="text" id="new_question_text">
				<button class="submit_button_add_question" type="submit">Dodaj Pitanje</button>
			</fieldset>

			<!-- set a specific question for a MT -->
			<fieldset class="question-set-box-admin">
				<h3>Odabir pitanja:</h3>
				<select id="q_list" name="customQuestionlist" class="q_list_admin">
					<!-- Content generated by call -->
				</select>
				
				<h3>Postavi pitanje na sljedeće MT:</h3>
				<select id="mt_list_q" name="mt" class="mt_list_q_admin">
					<!-- Content generated by call -->
				</select>

				<button class="submit_button_set_question" type="submit">Postavi pitanje</button>
			</fieldset>

			<!-- globally add new thanks text -->
			<fieldset class="thanks-add-box-admin">
				<h3>Dodavanje teksta kod zahvale:</h2>
				<input type="text" id="new_thanks_text">
				<button class="submit_button_thanks_message" type="submit">Dodaj Tekst</button>
			</fieldset>

			<!-- set a specific thanks for a MT -->
			<fieldset class="thanks-set-box-admin">
				<h3>Odabir teksta:</h3>
				<select id="thanks_list" name="customThankslist" class="thanks_list_admin">
					<!-- Content generated by call -->
				</select>
				
				<h3>Postavi tekst na sljedeće MT:</h3>
				<select id="mt_list_thanks" name="mt" class="mt_list_thanks_admin">
					<!-- Content generated by call -->
				</select>

				<button class="submit_button_set_thanks" type="submit">Postavi tekst</button>
			</fieldset>

			<fieldset class="ad-upload-box-admin">
				<p><a href="./ads/ad_pic.php">Postavke za Reklame</a></p>
			</fieldset>

		</div>
		<div id='vote_charts'>
			<canvas id="votesChartFirstQ" height="300px" width="1600"></canvas>
			<canvas id="votesChartSecondQ" height="42%"></canvas>
			<canvas id="votesChartThirdQ" height="42%"></canvas>
			<canvas id="votesChartFourthQ" height="42%"></canvas>
			<canvas id="votesRadarChart" height="50px"></canvas>
		</div>

		<div id="footer"><hr />&copy; Antonio Prcela. All rights reserved.</div>
	</body>
</html>
