<!DOCTYPE html>
<html lang="hr">

	<head>
		<title>Admin panel - Delete data</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilDelete.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
		<script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
		<script src="./script/scriptDeletemt.js" type="text/javascript"></script>
	</head>

	<body>
		<div id="goBack"><a href="javascript:window.close();">Back</a></div>
		
        <div id="delete_functions">
			<!-- MT to show -->
			<fieldset id="mt-choice-box-admin">
				<h3>Choose Place ID to delete:</h3>
				<select id="mt_list" name="mt" class="mt_list_admin">
					<!-- Content generated by call -->
				</select>
                <button class="submit_button_delete_mt" type="submit">Delete place</button>
                <div id="delConfirmation"></div>
			</fieldset>

			<!-- Question
			<fieldset id="question-del-box-admin">
				<h3>Chose question to delete:</h3>
				<select id="q_list" name="customQuestionlist" class="q_list_admin">
					<!-/- Content generated by call -/->
				</select>
                <button class="submit_button_delete_question" type="submit">Delete question</button>
                <div id="delConfirmation"></div>
			</fieldset> -->

			<!-- set a specific thanks for a MT -->
			<fieldset class="thanks-del-box-admin">
				<h3>Choose Info text to delete:</h3>
				<select id="thanks_list" name="customThankslist" class="thanks_list_admin">
					<!-- Content generated by call -->
				</select>
				<button class="submit_button_del_thanks" type="submit">Delete text</button>
				<div id="delConfirmationThanksText"></div>
			</fieldset>
        </div>

    </body>
</html>
