<!DOCTYPE html>
<html lang="hr">

	<head>
		<title>Adria Gastro - admin -panel - Targets</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilTarget.css" />
		<link rel="stylesheet" type="text/css" href="./css/jquery-ui-1.11.4.min.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
		<script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
		<script src="./script/scriptTarget.js" type="text/javascript"></script>
		<script src="./script/Chart.bundle-2.2.1.min.js" type="text/javascript"></script>
		<script src="./script/moment.min-2.14.1.js" type="text/javascript"></script>
	</head>

    <body>

        <div id="target-settings">
            <h2>Odaberite MT za koje želite podesiti targete:</h2>
            <select id="mt_list" name="mt" class="mt_list_admin">
                <!-- Content generated by call -->
            </select>
            <button class="submit_choice" type="submit">Odaberi MT</button>
            <hr />
            <div hidden id="set-target-values">
                <h2 id="grade-set-text">Željene ocjene za pitanja:</h2>
                
                <div id="target-range">
                    <p>Tjedan:</p>
                    <p>Mjesec:</p>
                    <p>Kvartal:</p>
                    <p>Godina:</p>
                </div>

                <!-- yeah, it's reverse order, year, quarter, month, week -->
                <h3>Koliko ste zadovoljni uslugom restorana?
                <input type="number" id="q_one_target_year" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_one_target_quarter" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_one_target_month" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_one_target_week" value="0" step="0.1" min="1" max="5"></h3>

                <h3>Koliko ste zadovoljni kvalitetom ponude?
                <input type="number" id="q_two_target_year" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_two_target_quarter" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_two_target_month" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_two_target_week" value="0" step="0.1" min="1" max="5"></h3>
                
                <h3>Koliko ste zadovoljni raznovrsnošću ponude?
                <input type="number" id="q_three_target_year" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_three_target_quarter" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_three_target_month" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_three_target_week" value="0" step="0.1" min="1" max="5"></h3>

                <h3 id="custom_question">
                <input type="number" id="q_four_target_year" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_four_target_quarter" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_four_target_month" value="0" step="0.1" min="1" max="5">
                <input type="number" id="q_four_target_week" value="0" step="0.1" min="1" max="5"></h3>

                <button class="submit_target_values" type="submit">Postavi vrijednosti</button>
            </div>
        </div>

	</body>
</html>
