<html lang="hr">

	<head>
		<title>Data as XML</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilXml.css" />
		<link rel="stylesheet" type="text/css" href="./css/jquery-ui-1.11.4.min.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
        <script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
        <script src="./script/moment.min-2.14.1.js" type="text/javascript"></script>
        <script src="./script/scriptXml.js" type="text/javascript"></script>
	</head>

	<body>
        <div id="goBack"><a href="javascript:window.close();">Back</a></div>

        <div id="xml_functions">
            <fieldset class="xml-box-admin">
                <h3>Get data by day/month/quarter/year</h3>
                <p></p>
                <hr />
                <input type="checkbox" name="mt_checkbox" id="mtCheckbox" value="MT">Get for this Place</br>
                <div id="showMtChoice">
                    <p>Choose place:</p>
                    <select id="mt_list" name="mt" class="mt_list_admin">
                        <!-- Content generated by call -->
                    </select>
                </div>

                <hr />
                <h3>FOR A SPECIFIC DA</h3>
                <h3>Choose day you want data for:</h3>
                <form action="" method="POST" enctype="multipart/form-data">
                    <input type="text" name="chosenDate" id="chosenDateD" class="date-picker-Day" value="">
                    <input id="submitButtonDay" type="submit" value="Dohvati podatke"></input>
                </form>

                <hr />
                <h3>FOR EVERY MONTH</h3>
                <p>Set year you want data from (all months of that Y):</p>
                <form action="" method="POST" enctype="multipart/form-data">
                    <input id="inputTextM" type="number" value="2016" step="1" min="2016" max="2999" />
                    <input id="submitButtonMonth" type="submit" value="Dohvati podatke"></input>
                </form>

                <hr />
                <h3>FOR A SPECIFIC QUARTER</h3>
                <p>Choose quarter:</p>
                <form id="quarterChoice" action="" method="POST" enctype="multipart/form-data">
                    <input type="radio" class="radio_item" value="1" name="q" id="q_1"/><label for="q_1">I. Kvartal</label></br>
					<input type="radio" class="radio_item" value="2" name="q" id="q_2"/><label for="q_2">II. Kvartal</label></br>
					<input type="radio" class="radio_item" value="3" name="q" id="q_3"/><label for="q_3">III. Kvartal</label></br>
					<input type="radio" class="radio_item" value="4" name="q" id="q_4"/><label for="q_4">IV. Kvartal</label></br>
                    <input id="submitButtonQuarter" type="submit" value="Dohvati podatke"></input>
                </form>

                <hr />
                <h3>YEARLY DATA</h3>
                <p>Choose year you want data from:</p>
                <form action="" method="POST" enctype="multipart/form-data">
                    <input id="inputTextY" type="number" value="2016" step="1" min="2016" max="2999" />
                    <input id="submitButtonYear" type="submit" value="Dohvati podatke"></input>
                </form>

            </fieldset>
        </div>

    </body>
</html>
