<html lang="hr">

	<head>
		<title>Adria Gastro - Dohvat tablice podataka</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="./images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="./css/stilXml.css" />
		<link rel="stylesheet" type="text/css" href="./css/jquery-ui-1.11.4.min.css" />
		<script src="./script/jquery-2.2.4.min.js" type="text/javascript"></script>
        <script src="./script/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
        <script src="./script/moment.min-2.14.1.js" type="text/javascript"></script>
        <script src="./script/scriptXml.js" type="text/javascript"></script>
	</head>

	<body>
        <div id="goBack"><a href="javascript:window.close();">Natrag</a></div>

        <div id="xml_functions">
            <fieldset class="xml-box-admin">
                <h3>Dohvaćanje podataka po danu/mjesecu/kvartalu/godini</h3>
                <p></p>
                <hr />
                <input type="checkbox" name="mt_checkbox" id="mtCheckbox" value="MT">Dohvati za sva MT</br>
                <div id="showMtChoice">
                    <p>Odaberite MT za prikaz glasova:</p>
                    <select id="mt_list" name="mt" class="mt_list_admin">
                        <!-- Content generated by call -->
                    </select>
                </div>

                <hr />
                <h3>ZA ODREĐENI DAN</h3>
                <h3>Odaberite dan za koji želite podatke:</h3>
                <form action="" method="POST" enctype="multipart/form-data">
                    <input type="text" name="chosenDate" id="chosenDateD" class="date-picker-Day" value="">
                    <input id="submitButtonDay" type="submit" value="Dohvati podatke"></input>
                </form>

                <hr />
                <h3>ZA SVAKI MJESEC</h3>
                <p>Unesite godinu za koju želite podatke po mjesecima:</p>
                <form action="" method="POST" enctype="multipart/form-data">
                    <input id="inputTextM" type="number" value="2016" step="1" min="2016" max="2999" />
                    <input id="submitButtonMonth" type="submit" value="Dohvati podatke"></input>
                </form>

                <hr />
                <h3>ZA ODREĐENI KVARTAL</h3>
                <p>Odaberite kvartal za koji želite podatke:</p>
                <form id="quarterChoice" action="" method="POST" enctype="multipart/form-data">
                    <input type="radio" class="radio_item" value="1" name="q" id="q_1"/><label for="q_1">I. Kvartal</label></br>
					<input type="radio" class="radio_item" value="2" name="q" id="q_2"/><label for="q_2">II. Kvartal</label></br>
					<input type="radio" class="radio_item" value="3" name="q" id="q_3"/><label for="q_3">III. Kvartal</label></br>
					<input type="radio" class="radio_item" value="4" name="q" id="q_4"/><label for="q_4">IV. Kvartal</label></br>
                    <input id="submitButtonQuarter" type="submit" value="Dohvati podatke"></input>
                </form>

                <hr />
                <h3>GODIŠNJI IZVJEŠTAJ</h3>
                <p>Unesite godinu za koju želite podatke:</p>
                <form action="" method="POST" enctype="multipart/form-data">
                    <input id="inputTextY" type="number" value="2016" step="1" min="2016" max="2999" />
                    <input id="submitButtonYear" type="submit" value="Dohvati podatke"></input>
                </form>

            </fieldset>
        </div>

    </body>
</html>
