<?php
    if(isset($_FILES['image'])){
        $errors = array();
        $file_name = $_FILES['image']['name'];
        $file_size = $_FILES['image']['size'];
        $file_tmp = $_FILES['image']['tmp_name'];
        $file_type = $_FILES['image']['type'];
        $file_ext = strtolower(end(explode('.',$_FILES['image']['name'])));

        list($width, $height) = getimagesize($file_tmp);

        if ($width != 740 && $height != 300){
            $errors[] = "The dimensions of the pic are invalid!";
        }

        $expensions = array("jpeg","jpg","png");

        if (in_array($file_ext, $expensions) === false) {
            $errors[] = "Filetype not supported!";
        }

        if ($file_size > 262144) {
            $errors[] = 'Size of the pic has to be lass than 256 KB!';
        }

        if (empty($errors) == true) {
            move_uploaded_file( $file_tmp, "./".$file_name );
        } else {
            echo '<div id="pic_error">';
            foreach($errors as $errMsg){
                print $errMsg . '</br>';
            }

            echo '</div>';
        }
    }
?>

<html lang="hr">

	<head>
		<title>Advertising pics</title>
		<meta http-equiv="Content-Type" content="text/html;charset='utf-8'" />
		<link rel="shortcut icon" href="../images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="../css/stilAds.css" />
		<link rel="stylesheet" type="text/css" href="../css/jquery-ui-1.11.4.min.css" />
		<script src="../script/jquery-2.2.4.min.js" type="text/javascript"></script>
		<script src="../script/scriptAds.js" type="text/javascript"></script>
	</head>

	<body>
        <div id="goBack"><a href="javascript:window.close();">Back</a></div>

        <div id="ads_functions">
            <!-- upload new ad pic -->
            <fieldset class="ad-upload-box-admin">
                <h3>Add new advertising picture:</h3>

                <form action="" method="POST" enctype="multipart/form-data">
                    <input type="file" name="image" /></br>
                    <input type="submit" value="Postavi sliku"></input>
                </form>
                <p>Supported formats: JPG, JPEG, PNG</br>
                Resolution has to be 740 x 300 pixels (w x h)</br>
                Max size: 256 KB</p>
            </fieldset>

            <!-- delete ad pic -->
            <fieldset class="ad-delete-box-admin">
                <h3>Delete pic:</h3>
                <select id="ad_list" name="ads_list" class="ads_list_admin">
                    <!-- Content generated by call -->
                </select>
                <button class="del_button_ad" type="submit">Delete pic</button>
                <div id="delConfirmation"></div>
            </fieldset>
        </div>

        <div class="ad-pics-box-admin">
            <h3>Preview of active pics:</h3>
            <div id="pics_preview">
                <!-- Content generated by call -->
            </div>
        </div>

    </body>
</html>
